---
- name: Create account
  hosts: all
  become: true
  vars:
    password: gabia
  tasks:
    - name: create user
      user:
        name: gplan 
    - name: set password
      user:
        name:  gplan
        password: "{{ password | password_hash('sha512')}}"
    - name: sudoers.d
      copy:
        content: |
          %gplan ALL=(ALL) NOPASSWD: ALL
        dest:  /etc/sudoers.d/gplan
        owner: root
        group: root
        mode: 0440
        validate: "/usr/sbin/visudo -c -f '%s'"

